
FROM debian:stretch
LABEL maintainer="github@github.com"


RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
RUN sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list
RUN sed -i '/stretch-updates/d' /etc/apt/sources.list

RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y build-essential libssl-dev default-libmysqlclient-dev clang valgrind netcat ruby ruby-dev ruby-bundler

WORKDIR /app
COPY . .

CMD ["script/test"]
