#!/bin/sh
# Bootstrap the application's environment.
set -e
cd "$(dirname $0)"/..

bundle config set --local path vendor/gems
bundle check 2>&1 > /dev/null || {
  bundle install "$@"
  bundle clean
}

script/build
