require "bundler/gem_tasks"
require "rake/extensiontask"
require "rake/testtask"

Rake::ExtensionTask.new do |ext|
  ext.name  = "cext"
  ext.ext_dir = "ext/trilogy-ruby"
  ext.lib_dir = "lib/trilogy"
end

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb']
  t.verbose = true
end
task :test => :compile

task :default => :test

task :console => :compile do
  sh "ruby -I lib -r trilogy -S irb"
end
